/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Setting;

import DAOs.FoodTypeDAO;
import Models.FoodType;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rodrigo.garcia
 */
public class CategoriesPanel extends javax.swing.JPanel {

    /**
     * Creates new form CategoriesPanel
     */
    public CategoriesPanel() {
        initComponents();
        init();
        initCategories();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tableCategories = new javax.swing.JTable();
        BtnAddCategories = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));
        setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(65534, 32767));
        setMinimumSize(new java.awt.Dimension(980, 523));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(980, 523));

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setPreferredSize(new java.awt.Dimension(478, 402));

        tableCategories.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jScrollPane2.setViewportView(tableCategories);

        BtnAddCategories.setText("Add");
        BtnAddCategories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddCategoriesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnAddCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 839, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnAddCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAddCategoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddCategoriesActionPerformed
        // TODO add your handling code here:
         new CategoriesAddFrame().setVisible(true);
    }//GEN-LAST:event_BtnAddCategoriesActionPerformed
    
    //Init the table with a default table
    public void init(){
    defaultTableModel = new javax.swing.table.DefaultTableModel(
            
            //Default table configurations
            new Object [][]{},
            new String[]{
                "ID", "Category Name", "Description"
            }
    ) 
            {
            Class[] types = new Class[]{
                java.lang.String.class,java.lang.String.class,java.lang.String.class,
            };
            boolean[] canEdit = new boolean[]{
                false, false,false
            };
            
            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        
        };
    //Add vaues to the panel table
    tableCategories.setModel(defaultTableModel);
}
    
    
    
    
    
    public void initCategories(){
        
        
        FoodTypeDAO foodTypeDao = new FoodTypeDAO();
        ArrayList<FoodType> foodTypes = new ArrayList<>();
        Object[] rowData = new Object[3];
        
        foodTypes = foodTypeDao.searchAll();
        
       
        
        for(int i = 0; i<foodTypes.size();i++){
        rowData[0] = foodTypes.get(i).getId();
        rowData[1] = foodTypes.get(i).getTypeName();
        rowData[2] = foodTypes.get(i).getDescription();
        defaultTableModel.addRow(rowData);
        }
        

    
    }
    

DefaultTableModel defaultTableModel;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAddCategories;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableCategories;
    // End of variables declaration//GEN-END:variables
}
