/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Setting;

import DAOs.CustomerDAO;
import Models.Customer;
import Utils.Settings;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author patricia.garcia
 */
public class CustomerUpdateFrame extends javax.swing.JFrame {

    /**
     * Creates new form CustomerAddFrame
     */
    public CustomerUpdateFrame() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelFName = new javax.swing.JLabel();
        LabelLName = new javax.swing.JLabel();
        LabelPhone = new javax.swing.JLabel();
        LabelEmail = new javax.swing.JLabel();
        LabelDescription = new javax.swing.JLabel();
        textFName = new javax.swing.JTextField();
        textLName = new javax.swing.JTextField();
        textPhone = new javax.swing.JTextField();
        textEmail = new javax.swing.JTextField();
        textDescription = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        LabelFName1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstId = new javax.swing.JList<>();

        setTitle("Add New Customer");

        LabelFName.setText("First Name");

        LabelLName.setText("Last Name");

        LabelPhone.setText("Phone");

        LabelEmail.setText("Email");
        LabelEmail.setToolTipText("");

        LabelDescription.setText("Description");

        textPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPhoneActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        LabelFName1.setText("ID");

        jScrollPane1.setViewportView(lstId);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(175, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClose)
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(LabelFName)
                                    .addGap(5, 5, 5))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelEmail)
                                    .addComponent(LabelDescription)
                                    .addComponent(LabelPhone)))
                            .addComponent(LabelLName)
                            .addComponent(LabelFName1))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textFName)
                            .addComponent(textLName)
                            .addComponent(textPhone)
                            .addComponent(textEmail)
                            .addComponent(textDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGap(49, 49, 49))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelFName1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LabelFName)
                            .addComponent(textFName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelLName)
                            .addComponent(textLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelPhone)
                            .addComponent(textPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addComponent(LabelEmail))
                    .addComponent(textEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(LabelDescription))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(textDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdate)
                    .addComponent(btnClose))
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("Update New Customer");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        //init(); 
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void textPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPhoneActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_textPhoneActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);

    }//GEN-LAST:event_btnCloseActionPerformed

 /*public void updateCustomer(){
     String fName = textFName.getText();
     String lName = textLName.getText();
     String phone = textPhone.getText();
     String email = textEmail.getText();
     String description = textDescription.getText();
     CustomerDAO customerDao = new CustomerDAO();
     
     customerDao.updateCustomer(fName, lName, phone, email, description);
     
     textFName.setText(null);
     textLName.setText(null);
     textPhone.setText(null);
     textEmail.setText(null);
     textDescription.setText(null)
 
 
 }*/
 
 private void init(){
 
     CustomerDAO customerDao = new CustomerDAO();
     ArrayList<Customer> customers = new ArrayList<>();
     defaultListModel = new DefaultListModel<String>();
     
     customers = customerDao.searchAll();
     
     
     for(int i = 0; i < customers.size() ; i++){
     
         defaultListModel.addElement(customers.get(i).getId());
     
     }
     
     lstId.setModel(defaultListModel);
 
 }
 

    
   DefaultListModel defaultListModel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelDescription;
    private javax.swing.JLabel LabelEmail;
    private javax.swing.JLabel LabelFName;
    private javax.swing.JLabel LabelFName1;
    private javax.swing.JLabel LabelLName;
    private javax.swing.JLabel LabelPhone;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstId;
    private javax.swing.JTextField textDescription;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textFName;
    private javax.swing.JTextField textLName;
    private javax.swing.JTextField textPhone;
    // End of variables declaration//GEN-END:variables
}
