/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Setting;

import DAOs.CustomerDAO;
import DAOs.FoodTypeDAO;
import Models.Customer;
import Models.FoodType;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rodrigo.garcia
 */
public class CustomerPanel extends javax.swing.JPanel {

    /**
     * 
     * 
     * Creates new form CustomerPanel
     */
    public CustomerPanel() {
        initComponents();
        init();
        initCustomer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCustomer = new javax.swing.JTable();
        BtnAddCustomer = new javax.swing.JButton();
        BtnUpdateCustomer = new javax.swing.JButton();
        BtnDeleteCustomer = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));
        setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        setPreferredSize(new java.awt.Dimension(980, 523));

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tableCustomer.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jScrollPane1.setViewportView(tableCustomer);

        BtnAddCustomer.setText("Add");
        BtnAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddCustomerActionPerformed(evt);
            }
        });

        BtnUpdateCustomer.setText("Update");
        BtnUpdateCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateCustomerActionPerformed(evt);
            }
        });

        BtnDeleteCustomer.setText("Delete");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnAddCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnUpdateCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnDeleteCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnDeleteCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnUpdateCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAddCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddCustomerActionPerformed
        // TODO add your handling code here:
        
        //setLayout(new BorderLayout());
        new CustomerAddFrame().setVisible(true);
    }//GEN-LAST:event_BtnAddCustomerActionPerformed

    private void BtnUpdateCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateCustomerActionPerformed
        // TODO add your handling code here:
        new CustomerUpdateFrame().setVisible(true);
    }//GEN-LAST:event_BtnUpdateCustomerActionPerformed

    
        public void init(){
    defaultTableModel = new javax.swing.table.DefaultTableModel(
            
            
            new Object [][]{},
            new String[]{
                "Customer id","Name", "Last Name", "Phone", "Email", "Description", "Created at", "Is Active"
            }
    ) 
            {
            Class[] types = new Class[]{
                java.lang.String.class,java.lang.String.class,java.lang.String.class,java.lang.String.class
                    ,java.lang.String.class,java.lang.String.class,java.lang.String.class,java.lang.String.class
            };
            boolean[] canEdit = new boolean[]{
                false, false, false, false, false, false, false, false
            };
            
            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        
        };
    tableCustomer.setModel(defaultTableModel);
}
    
    
    
    
    
    public void initCustomer(){
     
        CustomerDAO customerDao = new CustomerDAO();
        ArrayList<Customer> customers = new ArrayList<>();
        Object[] rowData = new Object[8];
        
        customers = customerDao.searchAll();
        
       
        
        for(int i = 0; i<customers.size();i++){
        rowData[0] = customers.get(i).getId();
        rowData[1] = customers.get(i).getFirstName();
        rowData[2] = customers.get(i).getLastName();
        rowData[3] = customers.get(i).getPhone();
        rowData[4] = customers.get(i).getEmail();
        rowData[5] = customers.get(i).getDescription();
        rowData[6] = customers.get(i).getCreatedAt();
        rowData[7] = customers.get(i).isIsActive();
        
        defaultTableModel.addRow(rowData);
        }
        

    
    }
    

DefaultTableModel defaultTableModel;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAddCustomer;
    private javax.swing.JButton BtnDeleteCustomer;
    private javax.swing.JButton BtnUpdateCustomer;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableCustomer;
    // End of variables declaration//GEN-END:variables
}
