/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Setting;

import java.awt.BorderLayout;
import java.awt.GridLayout;

/**
 *
 * @author PPuarat
 */
public class Setting extends javax.swing.JPanel {

    /**
     * Creates new form Settings
     */
    public Setting() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optionsPanel = new javax.swing.JPanel();
        btnCustomers = new javax.swing.JButton();
        btnUsers = new javax.swing.JButton();
        btnCategories = new javax.swing.JButton();
        btnMenufood = new javax.swing.JButton();
        dataPanel = new javax.swing.JPanel();

        optionsPanel.setBackground(new java.awt.Color(255, 255, 255));
        optionsPanel.setMaximumSize(new java.awt.Dimension(3267, 3267));
        optionsPanel.setPreferredSize(new java.awt.Dimension(700, 700));

        btnCustomers.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnCustomers.setText("Customer");
        btnCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomersActionPerformed(evt);
            }
        });

        btnUsers.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnUsers.setText("Staff");
        btnUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsersActionPerformed(evt);
            }
        });

        btnCategories.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnCategories.setText("Categories");
        btnCategories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriesActionPerformed(evt);
            }
        });

        btnMenufood.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnMenufood.setText("Menus");
        btnMenufood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenufoodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout optionsPanelLayout = new javax.swing.GroupLayout(optionsPanel);
        optionsPanel.setLayout(optionsPanelLayout);
        optionsPanelLayout.setHorizontalGroup(
            optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionsPanelLayout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMenufood, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
        optionsPanelLayout.setVerticalGroup(
            optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionsPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(btnCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMenufood, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dataPanel.setBackground(new java.awt.Color(255, 255, 204));
        dataPanel.setPreferredSize(new java.awt.Dimension(1500, 1500));
        dataPanel.setLayout(new javax.swing.BoxLayout(dataPanel, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(optionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(optionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1500, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenufoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenufoodActionPerformed
        // TODO add your handling code here:

        MenuPanel obj = new MenuPanel();
        //setLayout(new BorderLayout());
        dataPanel.removeAll();
        dataPanel.add(obj);//3rd argument is index
        dataPanel.repaint();
        dataPanel.revalidate();
    }//GEN-LAST:event_btnMenufoodActionPerformed

    private void btnCategoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriesActionPerformed
        // TODO add your handling code here:
        CategoriesPanel obj = new CategoriesPanel();
        //setLayout(new BorderLayout());
        dataPanel.removeAll();
        dataPanel.add(obj);//3rd argument is index
        dataPanel.repaint();
        dataPanel.revalidate();
    }//GEN-LAST:event_btnCategoriesActionPerformed

    private void btnUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsersActionPerformed
        // TODO add your handling code here:
        UserPanel obj = new UserPanel();
        //setLayout(new BorderLayout());
        dataPanel.removeAll();
        dataPanel.add(obj);//3rd argument is index
        dataPanel.repaint();
        dataPanel.revalidate();
    }//GEN-LAST:event_btnUsersActionPerformed

    private void btnCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomersActionPerformed
        // TODO add your handling code here:
        CustomerPanel obj = new CustomerPanel();
        //setLayout(new BorderLayout());
        dataPanel.removeAll();
        dataPanel.add(obj);//3rd argument is index
        dataPanel.repaint();
        dataPanel.revalidate();
    }//GEN-LAST:event_btnCustomersActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCategories;
    private javax.swing.JButton btnCustomers;
    private javax.swing.JButton btnMenufood;
    private javax.swing.JButton btnUsers;
    public javax.swing.JPanel dataPanel;
    private javax.swing.JPanel optionsPanel;
    // End of variables declaration//GEN-END:variables
}
