/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author PPuarat
 */
public class Application extends javax.swing.JPanel {

    /**
 * Creates new form applicationPanel
     */
    public Application() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
    public void init() {

        menuPanel = new javax.swing.JPanel();
        appPanel = new javax.swing.JPanel();

        menuPanel.setBackground(new java.awt.Color(255, 255, 0));
        menuPanel.setLayout(new java.awt.GridLayout(1, 0));
        add(menuPanel, java.awt.BorderLayout.PAGE_START);

        appPanel.setLayout(new java.awt.BorderLayout());
        add(appPanel);

//        orderDetail = new OrderDetail();
//        appPanel.add(orderDetail);
        Menu menu = new Menu(appPanel);

        menuPanel.add(menu);

    }
    private javax.swing.JPanel appPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPanel orderDetail;


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
