/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Views.Components.MenuButton;
import Views.Order.OrderDetail;
import Views.Order.OrderManagement;
import Views.Report.Report;
import Views.Setting.Setting;
import javax.swing.JPanel;

/**
 *
 * @author PPuarat
 */
public class Menu extends javax.swing.JPanel {

    private JPanel appPanel;
    private javax.swing.JButton btnNewOrder;
    private javax.swing.JButton btnOrders;
    private javax.swing.JButton btnReports;
    private javax.swing.JButton btnSettings;

    /**
     * Creates new form Menu
     */
    public Menu(JPanel inputJP) {
        appPanel = inputJP;
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridLayout(1, 0));
    }// </editor-fold>//GEN-END:initComponents
    private void btnActionPerformed(java.awt.event.ActionEvent evt, JPanel targetPanel) {
        // TODO add your handling code here:
        appPanel.removeAll();
        appPanel.add(targetPanel);
        appPanel.repaint();
        appPanel.revalidate();

    }

    private void init() {
        orderDetail = new OrderDetail();
        orderManagement = new OrderManagement();
        report = new Report();
        setting = new Setting();
        //Set default page orderDetail
        appPanel.add(orderDetail);

        btnNewOrder = new MenuButton("New Order");
        btnNewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                //Clear data in orderDetail
                orderDetail = new OrderDetail();
                btnActionPerformed(evt, orderDetail);
            }
        });

        btnOrders = new MenuButton("Orders");
        btnOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt, orderManagement);
            }
        });

        btnReports = new MenuButton("Reports");
        btnReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt, report);
            }
        });

        btnSettings = new MenuButton("Settings");
        btnSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt, setting);
            }
        });

        add(btnNewOrder);
        add(btnOrders);
        add(btnReports);
        add(btnSettings);
    }

    private javax.swing.JPanel orderDetail;
    private javax.swing.JPanel orderManagement;
    private javax.swing.JPanel report;
    private javax.swing.JPanel setting;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
