/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Order;

import Controller.OrderDetailController;
import Models.Food;
import Models.FoodType;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author PPuarat
 */
public class OrderDetail extends javax.swing.JPanel {

    /**
     * Creates new form OrderDetail
     */
    public OrderDetail() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        detailPanel = new javax.swing.JPanel();
        foodTypePanel = new javax.swing.JPanel();
        foodPanel = new javax.swing.JPanel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));

        detailPanel.setPreferredSize(new java.awt.Dimension(250, 300));

        javax.swing.GroupLayout detailPanelLayout = new javax.swing.GroupLayout(detailPanel);
        detailPanel.setLayout(detailPanelLayout);
        detailPanelLayout.setHorizontalGroup(
            detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 146, Short.MAX_VALUE)
        );
        detailPanelLayout.setVerticalGroup(
            detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        add(detailPanel);

        foodTypePanel.setBackground(new java.awt.Color(204, 255, 255));
        foodTypePanel.setPreferredSize(new java.awt.Dimension(175, 300));
        foodTypePanel.setLayout(new java.awt.GridLayout(0, 1, 5, 10));
        add(foodTypePanel);

        foodPanel.setBackground(new java.awt.Color(255, 255, 153));
        foodPanel.setPreferredSize(new java.awt.Dimension(250, 300));
        foodPanel.setLayout(new java.awt.GridLayout(0, 3, 5, 5));
        add(foodPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void init() {
        OrderDetailController orderDetailCon = new OrderDetailController();
        Map<String, ArrayList<Food>> map = orderDetailCon.loadFoods();
        displayFoods(map);
    }

    private void displayFoodTypes(ArrayList<FoodType> foodTypes) {

        foodTypesBTNList = new ArrayList<>();

        foodTypes.stream().map((foodType) -> new JButton(foodType.getTypeName())).map((button) -> {
            foodTypesBTNList.add(button);
            return button;
        }).forEachOrdered((button) -> {
            foodTypePanel.add(button);
        });
    }

    private void displayFoods(Map<String, ArrayList<Food>> map) {
        foodBTNList = new HashMap<>();
        foodTypesBTNList = new ArrayList<>();
        mapFoodPanel = new HashMap<>();

        for (String key : map.keySet()) {
            JButton btnFoodType = new JButton(key);
            foodTypesBTNList.add(btnFoodType);
            foodTypePanel.add(btnFoodType);

            //FOOD Panel
            JPanel foodPanelLoop = new JPanel();

            for (Food food : map.get(key)) {
                
                System.out.println(key +":"+food.getFoodName());
                
                JButton btnFood = new JButton(food.getFoodName());
                //Use Later
                foodBTNList.put(food.getId(),btnFood);
                
                foodPanelLoop.add(btnFood);//TODO Switch between these panels
                
                foodPanel.add(btnFood);//sample
                
            }
            //Food pane for each type of food
            mapFoodPanel.put(key, foodPanelLoop);//TODO Switch between these panels


        }

    }

    ArrayList<JButton> foodTypesBTNList;
    Map<Long, JButton> foodBTNList;
    Map<String, JPanel> mapFoodPanel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel detailPanel;
    private javax.swing.JPanel foodPanel;
    private javax.swing.JPanel foodTypePanel;
    // End of variables declaration//GEN-END:variables
}
