/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Order;

import Controller.OrderDetailController;
import Controller.OrderManagementController;
import Models.Order;
import Views.Order.Components.OrderListButton;
import java.util.ArrayList;
import java.util.Map;
import javax.swing.JButton;

/**
 *
 * @author PPuarat
 */
public class OrderManagement extends javax.swing.JPanel {

    /**
     * Creates new form OrderManagement
     */
    public OrderManagement() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1200, 675));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1200, 675));

        jPanel1.setLayout(new java.awt.GridLayout(1, 1));
        jScrollPane1.setViewportView(jPanel1);

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents

    private void init() {
        orderManagementCon = new OrderManagementController();
        displayOrder();
    }

    private void displayOrder() {
        ArrayList<Order> orders;
        orders = orderManagementCon.initOrderManagement();
//        System.out.println("Size of orders: "+orders.size());
        for (Order order : orders) {
            JButton orderBtn = new OrderListButton(order.getId() + "");
            System.out.println("Views.Order.OrderManagement.displayOrder()");
            
//            orderBtn.addActionListener((java.awt.event.ActionEvent evt) -> {
//                //switchFoodPanel(evt, key);
//            });
            jPanel1.add(orderBtn);
        }
    }
    OrderManagementController orderManagementCon;
    Map<Long, JButton> orderBtnMap;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
